post_type:
  - name: wolfie-book
    singular: book    # optional
    plural: books     # optional
    # taxonomies:       # optional this are only names of already registered taxonomies | it connects post type to taxonomies | taxonomy ealier needs to be declared
     # - wolfie-book
     # - wolfie-book-tag
    # supports:       # optional
    #   - editor
    #   - title
    #   - thumbnail
    #   - excerpt
    show_in_rest: true     # optional turn on / off gutenberg (default true thus gutenberg is on)
  - name: article
    show_in_rest: false     # optional turn on / off gutenberg (default true thus gutenberg is on)