comment_meta:
  - name: wolfie metabox
    prefix: wolfie
    or_where: 
      - state: current_user_capability = manage_options                      # limits permissions to view and change
      # - state: current_user_id = 99                                          # limits permissions to view and change
      # - state: current_user_role = administrator                             # limits permissions to view and change
    # where: # "where" is narrowing, "or_where" is extending 
      # - state: current_user_capability = manage_options                      # limits permissions to view and change
      # - state: current_user_id = 99                                          # limits permissions to view and change
      # - state: current_user_role = administrator                               # limits permissions to view and change
    fields: 
      - type: text
        name: Notification Email