taxonomy:                   # register custom taxonomy each name is seprate taxonomy and can be added to subpage to settings_page # optional
  - name: wolfie-event
    singular: event
    plural: events
    public: true
    hierarchical: true
    rewrite:
      slug: wolfie-events-category
    show_in_menu:  crb_carbon_fields_container_wolfie_events.php      # display it as subpage to setting page
    position_in_menu: 1
  - name: wolfie-event-tag
    singular: event
    plural: events
    public: true
    hierarchical: false
    rewrite:
      slug: wolfie-events-tag
    show_in_menu:  crb_carbon_fields_container_wolfie_events.php
    position_in_menu: 1


post_type:                # register custom post type # optional
  - name: wolfie-event
    singular: event
    plural: events
    show_in_menu: crb_carbon_fields_container_wolfie_events.php     # it adds default list of the posts to parent page (optional)
    taxonomies: # this are only names of already registered taxonomies | it connects post type to taxonomies | taxonomy ealier needs to be declared # optional
     - wolfie-event
     - wolfie-event-tag

settings_page:                       # each name is spreate page # optional
  - name: Wolfie Events              # required
    prefix: wolfieevents             # optional
    # menu_title: fix images         # optional
    # parent: tools.php              # optional
    # order: 9999                    # optional
    icon: dashicons-carrot           # optional dashicons class or url to image
    # fields:                        # optional
    #   - type: text
    #     name: First Name
    #     # label: 'First Name'
    #   - type: text
    #     name: Last Name
    #     # label: 'Last Name'
    #   - type: text
    #     name: Position
    #     # label: 'Position'
  - name: Wolfie Events Settings
    prefix: wolfieevents                                              # optional
    menu_title: Settings                                              # optional
    parent: crb_carbon_fields_container_wolfie_events.php             # optional - added ad submenu of above setting page
    # order: 9999                                                     # optional
    # icon: dashicons-carrot                                          # optional dashicons class or url to image
    fields:
      - type: text
        name: First Name
        # label: 'First Name'                                         # optional
      - type: text
        name: Last Name
        # label: 'Last Name'                                          # optional
      - type: text
        name: Position
        # label: 'Position'                                           # optional